NEON_DB_HOST="postgresql://neondb_owner:npg_zPrfGT7U3hDB@ep-silent-snow-aejytqa2-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
NEON_DB_DATABASE="neondb"
NEON_DB_USER="neondb_owner"
NEON_DB_PASSWORD="npg_zPrfGT7U3hDB"
NEON_DB_PORT="5432"